service: serverless-users-service
frameworkVersion: "3"

plugins:
  - serverless-plugin-typescript
  - serverless-offline

# Configurar cómo se empaca cada función
package:
  individually: true # Cada función se empaca por separado
  patterns:
    - "!**/*.test.ts"
    - "!**/*.spec.ts"
    - "!README.md"
    - "!TODO.md"
    - "!DONE.md"
    - "!.git/**" # Excluir git
    - "!node_modules/.cache/**" # Excluir cache

provider:
  name: aws
  runtime: nodejs20.x
  architecture: arm64
  stage: ${opt:stage, 'dev'}
  region: us-east-1

  logRetentionInDays: 7

  httpApi:
    cors:
      allowedOrigins:
        - "*"
      allowedHeaders:
        - "*"
      allowedMethods:
        - "*"
      allowCredentials: false

  # Obligatorio mapear variables de entorno
  environment:
    NODE_ENV: ${env:STAGE, 'dev'}
    NODE_OPTIONS: --enable-source-maps
    REGION: ${env:REGION, 'us-east-1'}
    # Variables específicas por stage
    STAGE: ${sls:stage}
    # DynamoDB
    DYNAMODB_ENDPOINT: ${env:DYNAMODB_ENDPOINT, 'http://localhost:4566'}
    USERS_TABLE: ${env:USERS_TABLE, 'users-service-db'}
    # SQS Queues
    USER_CREATED_QUEUE_URL: ${env:USER_CREATED_QUEUE_URL, 'http://localhost:4566/000000000000/user-created-queue'}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Query
            - dynamodb:Scan
          Resource:
            - arn:aws:dynamodb:${env:REGION, self:provider.region}:${env:AWS_ACCOUNT_ID, '000000000000'}:table/${env:USERS_TABLE, 'users-service-db'}
            - arn:aws:dynamodb:${env:REGION, self:provider.region}:${env:AWS_ACCOUNT_ID, '000000000000'}:table/${env:USERS_TABLE, 'users-service-db'}/index/*
        - Effect: Allow
          Action:
            - sqs:SendMessage
          Resource:
            - arn:aws:sqs:${self:provider.region}:${env:AWS_ACCOUNT_ID, '000000000000'}:user-created-queue

# Por ahora lo dejamos vacío: vas a ir agregando handlers poco a poco.
functions:
  healthCheck:
    handler: src/functions/health/health-check.handler
    events:
      - httpApi:
          method: GET
          path: /health
  createUser:
    handler: src/functions/users/create.handler
    events:
      - httpApi:
          method: POST
          path: /users
  getUserById:
    handler: src/functions/users/get-by-id.handler
    events:
      - httpApi:
          method: GET
          path: /users/{id}
  getUserByEmail:
    handler: src/functions/users/get-by-email.handler
    events:
      - httpApi:
          method: GET
          path: /users/by-email
  listUsers:
    handler: src/functions/users/list.handler
    events:
      - httpApi:
          method: GET
          path: /users
  updateUser:
    handler: src/functions/users/update.handler
    events:
      - httpApi:
          method: PUT
          path: /users/{id}

# resources:
#   Resources:
#     UsersTable:
#       Type: AWS::DynamoDB::Table
#       Properties:
#         TableName: ${self:custom.usersTableName}
#         BillingMode: PAY_PER_REQUEST
#         AttributeDefinitions:
#           - AttributeName: id
#             AttributeType: S
#           - AttributeName: email
#             AttributeType: S
#         KeySchema:
#           - AttributeName: id
#             KeyType: HASH
#         GlobalSecondaryIndexes:
#           - IndexName: email-index
#             KeySchema:
#               - AttributeName: email
#                 KeyType: HASH
#             Projection:
#               ProjectionType: ALL
#         PointInTimeRecoverySpecification:
#           PointInTimeRecoveryEnabled: true

#   Outputs:
#     UsersTableName:
#       Value: ${self:custom.usersTableName}
